# Generated by Django 5.1.15 on 2026-08-28 15:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(default='Information Technology', max_length=100)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=150)),
                ('job_description', models.TextField(blank=True, default='')),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Package in LPA (Lakhs Per Annum)', max_digits=6)),
                ('eligibility_gpa', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('drive_date', models.DateField()),
                ('application_deadline', models.DateTimeField()),
                ('location', models.CharField(default='Campus Placement Auditorium', max_length=150)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placements.company')),
            ],
            options={
                'verbose_name': 'Placement Drive',
                'verbose_name_plural': 'Placement Drives',
                'ordering': ['-drive_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('OFFERED', 'Offer Received'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Offer Accepted')], default='APPLIED', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('offer_letter_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.student')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('drive', 'student')},
            },
        ),
    ]
