# Generated by Django 5.1.15 on 2026-08-28 17:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_external_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_internal_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(default='Fall 2026', max_length=30),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('GRADING', 'Grading in Progress'), ('UNDER_REVIEW', 'Under HOD Review'), ('PUBLISHED', 'Published / Results Declared')], default='SCHEDULED', max_length=25),
        ),
        migrations.AddField(
            model_name='examresult',
            name='external_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='examresult',
            name='internal_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_verified_by_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
