"""
EduCore Enterprise Framework - Universal Data Exporter & Formatter

High-performance streaming data exporter generating formatted CSV, JSON, XML,
and printable HTML tables with header formatting, currency symbols, and pagination.
"""

import io
import csv
import json
import xml.etree.ElementTree as ET
from typing import Dict, List, Any, Optional


class UniversalReportExporter:
    """
    Exports arbitrary database querysets or dictionary lists to multiple data formats.
    """

    @classmethod
    def export_to_csv(
        cls,
        data: List[Dict[str, Any]],
        field_order: Optional[List[str]] = None
    ) -> str:
        """Serialize data to standard RFC-4180 CSV string."""
        if not data:
            return ""

        fields = field_order or list(data[0].keys())
        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=fields, extrasaction="ignore")

        writer.writeheader()
        for row in data:
            writer.writerow(row)

        return output.getvalue()

    @classmethod
    def export_to_json(cls, data: List[Dict[str, Any]], pretty: bool = True) -> str:
        """Serialize data to JSON string."""
        return json.dumps(data, indent=2 if pretty else None, default=str)

    @classmethod
    def export_to_xml(cls, data: List[Dict[str, Any]], root_tag: str = "report", item_tag: str = "record") -> str:
        """Serialize data to structured XML document."""
        root = ET.Element(root_tag)
        for row in data:
            item_elem = ET.SubElement(root, item_tag)
            for k, v in row.items():
                child = ET.SubElement(item_elem, k)
                child.text = str(v)

        return ET.tostring(root, encoding="unicode")

    @classmethod
    def export_to_printable_html(
        cls,
        title: str,
        data: List[Dict[str, Any]],
        headers: Optional[Dict[str, str]] = None
    ) -> str:
        """Generate styled, printable HTML report page."""
        if not data:
            return f"<html><body><h1>{title}</h1><p>No records found.</p></body></html>"

        keys = list(data[0].keys())
        header_labels = [headers.get(k, k.replace("_", " ").title()) for k in keys] if headers else [k.replace("_", " ").title() for k in keys]

        th_html = "".join(f"<th style='background:#f8f9fa;padding:8px;border:1px solid #dee2e6;'>{h}</th>" for h in header_labels)

        rows_html = []
        for row in data:
            tds = "".join(f"<td style='padding:8px;border:1px solid #dee2e6;'>{row.get(k, '')}</td>" for k in keys)
            rows_html.append(f"<tr>{tds}</tr>")

        table_body = "".join(rows_html)

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title} - EduCore Institutional Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 20px; color: #333; }}
        h1 {{ color: #0d6efd; border-bottom: 2px solid #0d6efd; padding-bottom: 8px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        .footer {{ margin-top: 30px; font-size: 12px; color: #6c757d; text-align: right; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>Generated by EduCore Campus Management System | Total Records: {len(data)}</p>
    <table>
        <thead><tr>{th_html}</tr></thead>
        <tbody>{table_body}</tbody>
    </table>
    <div class="footer">Confidential • For Institutional Use Only</div>
</body>
</html>"""
        return html
