# Generated by Django 5.1.15 on 2026-08-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('qualification', models.CharField(blank=True, default='Ph.D.', max_length=150)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('office_room', models.CharField(blank=True, default='', max_length=50)),
                ('office_hours', models.CharField(blank=True, default='Mon-Fri 2:00 PM - 4:00 PM', max_length=150)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
